#10.0.117.68/byd_geoeva/dotnet_runtime_with_python11:v8.0
# 使用 辉少的dotnet环境 作为基础镜像
FROM 10.0.117.68/byd_test/dotnet_runtime:8.0

#apt-get update 并且安装python环境
RUN \
    # 步骤1：彻底清理所有现存的 apt 源配置
    rm -f /etc/apt/sources.list && \
    rm -rf /etc/apt/sources.list.d/* && \
    \
    # 步骤2：写入全新的、唯一的清华大学镜像源
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free" > /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian-security bookworm-security main contrib non-free" >> /etc/apt/sources.list && \
    \
    # 步骤3：更新并安装
    apt-get update && \
    apt-get install -y --no-install-recommends python3.11 python3-pip

# 安装系统依赖，包括字体、vim 和 tzdata
RUN apt-get install -y --no-install-recommends \
    fonts-wqy-microhei \
    fonts-wqy-zenhei \
    vim \
    tzdata

# 配置操作系统的时区（同步 /etc/localtime 与 /etc/timezone）
# 设置时区变量（HK时区）
RUN ln -snf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime && \
    echo "Asia/Hong_Kong" > /etc/timezone

# 安装geopandas的编译依赖
RUN apt-get install -y --no-install-recommends \
    gdal-bin \
    libgdal-dev \
    g++ \
    python3.11-venv \
    && apt-get clean

# 步骤1: 创建一个虚拟环境
RUN python3 -m venv /opt/venv

# 步骤2: 将venv的bin目录永久性地添加到 PATH
ENV PATH="/opt/venv/bin:$PATH"


# 安装所需的 Python 库
# 安装也可以用 pip install -r requirements.txt 的方式。
# 现在写死提效。不用每次都找requirements.txt
RUN pip install --no-cache-dir \
    loguru==0.7.2 \
    numpy==2.0.1 \
    pyproj==3.6.1 \
    geopandas==1.0.1 \
    shapely==2.0.4 \
    pydantic==2.8.2 \
    jira==3.8.0 \
    pandas==2.2.3 \
    GeoAlchemy2==0.15.1 \
    SQLAlchemy==1.4.54 \
    defusedxml~=0.7.1 \
    pillow~=11.0.0 \
    zipp~=3.20.2 \
    setuptools~=70.0.0 \
    pytz~=2024.2 \
    cffi~=1.17.1 \
    six~=1.16.0 \
    python-dateutil~=2.9.0.post0 \
    contourpy~=1.3.0 \
    fonttools~=4.54.1 \
    scipy~=1.13.1 \
    packaging~=24.1 \
    pyparsing~=3.2.0 \
    cycler~=0.12.1 \
    kiwisolver~=1.4.7 \
    fiona==1.10.1 \
    geojson~=3.1.0 \
    tqdm==4.67.1 \
    PyYAML~=6.0.2 \
    matplotlib~=3.9.0 \
    pandera~=0.24.0