#ifndef _ROAD_MAPPING_VERSION_H__
#define _ROAD_MAPPING_VERSION_H__

#define ROAD_MAPPING_MAJOR_VERSION 3
#define ROAD_MAPPING_MINOR_VERSION 9
#define ROAD_MAPPING_PATCH_VERSION 0

//版本号拼接
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define ROAD_MAPPING_VERSION_STRING TOSTRING(ROAD_MAPPING_MAJOR_VERSION) "."                                     TOSTRING(ROAD_MAPPING_MINOR_VERSION) "."                                     TOSTRING(ROAD_MAPPING_PATCH_VERSION)  

#endif
