// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example.proto
// Protobuf C++ Version: 5.27.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_example_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_example_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_example_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_example_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_example_2eproto;
class add_req;
struct add_reqDefaultTypeInternal;
extern add_reqDefaultTypeInternal _add_req_default_instance_;
class add_rsp;
struct add_rspDefaultTypeInternal;
extern add_rspDefaultTypeInternal _add_rsp_default_instance_;
class hello_push;
struct hello_pushDefaultTypeInternal;
extern hello_pushDefaultTypeInternal _hello_push_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class hello_push final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:hello_push) */ {
 public:
  inline hello_push() : hello_push(nullptr) {}
  ~hello_push() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR hello_push(
      ::google::protobuf::internal::ConstantInitialized);

  inline hello_push(const hello_push& from) : hello_push(nullptr, from) {}
  inline hello_push(hello_push&& from) noexcept
      : hello_push(nullptr, std::move(from)) {}
  inline hello_push& operator=(const hello_push& from) {
    CopyFrom(from);
    return *this;
  }
  inline hello_push& operator=(hello_push&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const hello_push& default_instance() {
    return *internal_default_instance();
  }
  static inline const hello_push* internal_default_instance() {
    return reinterpret_cast<const hello_push*>(
        &_hello_push_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(hello_push& a, hello_push& b) { a.Swap(&b); }
  inline void Swap(hello_push* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(hello_push* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  hello_push* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<hello_push>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const hello_push& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const hello_push& from) { hello_push::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(hello_push* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "hello_push"; }

 protected:
  explicit hello_push(::google::protobuf::Arena* arena);
  hello_push(::google::protobuf::Arena* arena, const hello_push& from);
  hello_push(::google::protobuf::Arena* arena, hello_push&& from) noexcept
      : hello_push(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHelloFieldNumber = 1,
  };
  // string hello = 1;
  void clear_hello() ;
  const std::string& hello() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_hello(Arg_&& arg, Args_... args);
  std::string* mutable_hello();
  PROTOBUF_NODISCARD std::string* release_hello();
  void set_allocated_hello(std::string* value);

  private:
  const std::string& _internal_hello() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hello(
      const std::string& value);
  std::string* _internal_mutable_hello();

  public:
  // @@protoc_insertion_point(class_scope:hello_push)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      24, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_hello_push_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr hello_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_example_2eproto;
};
// -------------------------------------------------------------------

class add_rsp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:add_rsp) */ {
 public:
  inline add_rsp() : add_rsp(nullptr) {}
  ~add_rsp() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR add_rsp(
      ::google::protobuf::internal::ConstantInitialized);

  inline add_rsp(const add_rsp& from) : add_rsp(nullptr, from) {}
  inline add_rsp(add_rsp&& from) noexcept
      : add_rsp(nullptr, std::move(from)) {}
  inline add_rsp& operator=(const add_rsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline add_rsp& operator=(add_rsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const add_rsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const add_rsp* internal_default_instance() {
    return reinterpret_cast<const add_rsp*>(
        &_add_rsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(add_rsp& a, add_rsp& b) { a.Swap(&b); }
  inline void Swap(add_rsp* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(add_rsp* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  add_rsp* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<add_rsp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const add_rsp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const add_rsp& from) { add_rsp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(add_rsp* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "add_rsp"; }

 protected:
  explicit add_rsp(::google::protobuf::Arena* arena);
  add_rsp(::google::protobuf::Arena* arena, const add_rsp& from);
  add_rsp(::google::protobuf::Arena* arena, add_rsp&& from) noexcept
      : add_rsp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultFieldNumber = 1,
  };
  // int32 result = 1;
  void clear_result() ;
  ::int32_t result() const;
  void set_result(::int32_t value);

  private:
  ::int32_t _internal_result() const;
  void _internal_set_result(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:add_rsp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_add_rsp_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::int32_t result_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_example_2eproto;
};
// -------------------------------------------------------------------

class add_req final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:add_req) */ {
 public:
  inline add_req() : add_req(nullptr) {}
  ~add_req() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR add_req(
      ::google::protobuf::internal::ConstantInitialized);

  inline add_req(const add_req& from) : add_req(nullptr, from) {}
  inline add_req(add_req&& from) noexcept
      : add_req(nullptr, std::move(from)) {}
  inline add_req& operator=(const add_req& from) {
    CopyFrom(from);
    return *this;
  }
  inline add_req& operator=(add_req&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const add_req& default_instance() {
    return *internal_default_instance();
  }
  static inline const add_req* internal_default_instance() {
    return reinterpret_cast<const add_req*>(
        &_add_req_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(add_req& a, add_req& b) { a.Swap(&b); }
  inline void Swap(add_req* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(add_req* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  add_req* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<add_req>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const add_req& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const add_req& from) { add_req::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(add_req* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "add_req"; }

 protected:
  explicit add_req(::google::protobuf::Arena* arena);
  add_req(::google::protobuf::Arena* arena, const add_req& from);
  add_req(::google::protobuf::Arena* arena, add_req&& from) noexcept
      : add_req(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLeftFieldNumber = 1,
    kRightFieldNumber = 2,
  };
  // int32 left = 1;
  void clear_left() ;
  ::int32_t left() const;
  void set_left(::int32_t value);

  private:
  ::int32_t _internal_left() const;
  void _internal_set_left(::int32_t value);

  public:
  // int32 right = 2;
  void clear_right() ;
  ::int32_t right() const;
  void set_right(::int32_t value);

  private:
  ::int32_t _internal_right() const;
  void _internal_set_right(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:add_req)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_add_req_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::int32_t left_;
    ::int32_t right_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_example_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// add_req

// int32 left = 1;
inline void add_req::clear_left() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_ = 0;
}
inline ::int32_t add_req::left() const {
  // @@protoc_insertion_point(field_get:add_req.left)
  return _internal_left();
}
inline void add_req::set_left(::int32_t value) {
  _internal_set_left(value);
  // @@protoc_insertion_point(field_set:add_req.left)
}
inline ::int32_t add_req::_internal_left() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.left_;
}
inline void add_req::_internal_set_left(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_ = value;
}

// int32 right = 2;
inline void add_req::clear_right() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_ = 0;
}
inline ::int32_t add_req::right() const {
  // @@protoc_insertion_point(field_get:add_req.right)
  return _internal_right();
}
inline void add_req::set_right(::int32_t value) {
  _internal_set_right(value);
  // @@protoc_insertion_point(field_set:add_req.right)
}
inline ::int32_t add_req::_internal_right() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.right_;
}
inline void add_req::_internal_set_right(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_ = value;
}

// -------------------------------------------------------------------

// add_rsp

// int32 result = 1;
inline void add_rsp::clear_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = 0;
}
inline ::int32_t add_rsp::result() const {
  // @@protoc_insertion_point(field_get:add_rsp.result)
  return _internal_result();
}
inline void add_rsp::set_result(::int32_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:add_rsp.result)
}
inline ::int32_t add_rsp::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.result_;
}
inline void add_rsp::_internal_set_result(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = value;
}

// -------------------------------------------------------------------

// hello_push

// string hello = 1;
inline void hello_push::clear_hello() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hello_.ClearToEmpty();
}
inline const std::string& hello_push::hello() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:hello_push.hello)
  return _internal_hello();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void hello_push::set_hello(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hello_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:hello_push.hello)
}
inline std::string* hello_push::mutable_hello() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_hello();
  // @@protoc_insertion_point(field_mutable:hello_push.hello)
  return _s;
}
inline const std::string& hello_push::_internal_hello() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hello_.Get();
}
inline void hello_push::_internal_set_hello(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hello_.Set(value, GetArena());
}
inline std::string* hello_push::_internal_mutable_hello() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.hello_.Mutable( GetArena());
}
inline std::string* hello_push::release_hello() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:hello_push.hello)
  return _impl_.hello_.Release();
}
inline void hello_push::set_allocated_hello(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hello_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.hello_.IsDefault()) {
          _impl_.hello_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hello_push.hello)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_example_2eproto_2epb_2eh
